version: "3.8"
services:
    eth-deposit-tracker:
        build: .
        image: eth-deposit-tracker
        container_name: eth-deposit-tracker
        ports:
            - "3000:3000"
        env_file:
            - .env
